[2022-12-25T08:46:01.544+0000] {taskinstance.py:1081} INFO - Dependencies not met for <TaskInstance: dag_with_python_dependencies_v03.get_etl manual__2022-12-25T02:43:02.057968+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-12-25T08:46:01.605+0000] {local_task_job.py:98} INFO - Task is not able to be run
