[2022-12-25T02:48:04.380+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_etl scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2022-12-25T02:48:52.021+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_etl scheduled__2021-10-12T00:00:00+00:00 [queued]>
[2022-12-25T02:48:53.134+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T02:48:54.754+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-25T02:48:55.015+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T08:46:01.601+0000] {taskinstance.py:1081} INFO - Dependencies not met for <TaskInstance: dag_with_python_dependencies_v03.get_etl scheduled__2021-10-12T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-12-25T08:46:01.656+0000] {local_task_job.py:98} INFO - Task is not able to be run
