[2022-12-25T11:07:11.523+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [queued]>
[2022-12-25T11:07:11.657+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [queued]>
[2022-12-25T11:07:11.663+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:07:11.667+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-25T11:07:11.673+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:07:11.807+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 11:06:58.079596+00:00
[2022-12-25T11:07:11.848+0000] {standard_task_runner.py:55} INFO - Started process 2788 to run task
[2022-12-25T11:07:11.907+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-25T11:06:58.079596+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmp6fy__r7d']
[2022-12-25T11:07:11.928+0000] {standard_task_runner.py:83} INFO - Job 230: Subtask extract_test
[2022-12-25T11:07:12.273+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [running]> on host cc86156a81c5
[2022-12-25T11:07:12.530+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T11:06:58.079596+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T11:06:58.079596+00:00
[2022-12-25T11:07:13.012+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 40, in hello
    stream.add_rules(tweepy.StreamRule("Gempa Cianjur"))
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 683, in add_rules
    endpoint_parameters=("dry_run",), json=json, data_type=StreamRule
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/client.py", line 130, in _make_request
    json=json, user_auth=user_auth)
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/client.py", line 98, in request
    raise Unauthorized(response)
tweepy.errors.Unauthorized: 401 Unauthorized
Unauthorized
[2022-12-25T11:07:13.061+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221225T110658, start_date=20221225T110711, end_date=20221225T110713
[2022-12-25T11:07:13.097+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 230 for task extract_test (401 Unauthorized
Unauthorized; 2788)
[2022-12-25T11:07:13.154+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-25T11:07:13.203+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
